### ISSUE TITLE
[BUG/ISSUE] broken texture for not supported books

### ISSUE THREAD

**Issue by VaporeonScripts** [CERBON-s-Comissions/Beautiful-Enchanted-Books#1]
neoforge 1.21.1 .83
os: arch
latest version (2.0.0)
![image](https://github.com/user-attachments/assets/d2df0f40-e103-4560-8d15-1e3db8288ad6)

**Comment by VaporeonScripts** [comment]
so?

**Comment by CerbonXD** [comment]
The version 2.0.0 was re-released today, the problem should now be fixed. I will close this issue but feel free to reopen it if needed.
